graph TD
    A[div.z-calendars] --> B[div.z-calendars-body]
    B --> C[div.z-calendars-inner]
    C --> D[div.z-calendars-week]

    D --> E[div.z-calendars-week-header]
    D --> F[div.z-calendars-week-body]

    E --> G[table.z-calendars-week-header-cnt]
    G --> H[tr.z-calendars-day-header]
    G --> I[tr.z-calendars-daylong]

    H --> H1[th.z-calendars-timezone]
    H --> H2[th.z-calendars-day-of-week x7]
    H --> H3[th.z-calendars-day-of-week-end]

    H2 --> H2A[div.z-calendars-day-of-week-inner]
    H2A --> H2B[div.z-calendars-day-of-week-cnt]
    H2B --> H2C[Day name]
    H2B --> H2D[div.z-calendars-day-of-week-fmt]

    I --> I1[td.z-calendars-daylong-body]
    I1 --> I2[div.z-calendars-daylong-inner]
    I2 --> I3[table.z-calendars-daylong-cnt]
    I3 --> I4[td.z-calendars-daylong-evt x7]

    F --> J[table.z-calendars-week-cnt]
    J --> K[tr timezone]
    J --> L[tr content]

    K --> K1[td.timezone-end <br/>empty spacer]
    K --> K2[td colspan=7  <br/> show hour]
    K2 --> K3[div.z-calendars-hour]
    K3 --> K4[div.z-calendars-hour-inner]
    K4 --> K5[div.z-calendars-hour-sep x24 <br/>each day's hour slot ]

    L --> L1[td.z-calendars-timezone]
    L1 --> L2[div.z-calendars-hour-of-day x24 <br/> left header - hour slot]

    L --> L3[td.z-calendars-week-day x7]
    L3 --> L4[div.z-calendars-week-day-cnt]

    classDef default fill:#f9f9f9,stroke:#333,stroke-width:1px,color:black;
    classDef header fill:#E3F2FD,stroke:#333,stroke-width:1px;
    classDef daylong fill:#F1F8E9,stroke:#333,stroke-width:1px;
    classDef hourGrid fill:#FCE4EC,stroke:#333,stroke-width:1px;
    classDef content fill:#FFF8E1,stroke:#333,stroke-width:1px;

    class A,B,C,D default;
    class E,G,H,H1,H2,H3,H2A,H2B,H2C,H2D header;
    class I,I1,I2,I3,I4 daylong;
    class K,K1,K2,K3,K4,K5 hourGrid;
    class L,L1,L2,L3,L4 content;